"""Load seeded food price estimates into PostgreSQL.

Usage:
    python data/scripts/load_price_estimates_to_db.py --version-tag v1.1.0-price

The script reads the normalized price seed generated by `seed_prices.py` and
upserts each estimate into the dedicated `food_price_estimates` table by
matching `canonical_key` against `foods.canonical_key`.
"""

from __future__ import annotations

import argparse
import json
import os
from pathlib import Path
from typing import Any

import psycopg
from dotenv import load_dotenv


ROOT_DIR = Path(__file__).resolve().parents[2]
DEFAULT_PRICE_PATH = ROOT_DIR / "data" / "price_defaults.json"

load_dotenv(ROOT_DIR / "backend" / ".env")


def _database_url() -> str:
    db_url = os.getenv("DATABASE_URL", "")
    if not db_url:
        raise RuntimeError("DATABASE_URL is not configured")
    return db_url


def _clean_text(value: object) -> str:
    if value is None:
        return ""
    text = str(value).strip()
    if text.lower() in {"nan", "null", "none"}:
        return ""
    return text


def _to_int(value: object) -> int:
    text = _clean_text(value)
    if not text:
        return 0
    try:
        return int(float(text))
    except ValueError:
        return 0


def _to_float(value: object) -> float:
    text = _clean_text(value)
    if not text:
        return 0.0
    try:
        return float(text)
    except ValueError:
        return 0.0


def _load_json(path: Path) -> dict[str, Any]:
    if not path.exists():
        raise FileNotFoundError(f"Price defaults not found: {path}")
    with path.open("r", encoding="utf-8") as handle:
        loaded = json.load(handle)
    if not isinstance(loaded, dict):
        raise ValueError("Price defaults file must contain a JSON object")
    return loaded


def _ensure_dataset_version(cur: psycopg.Cursor, version_tag: str, source_manifest: dict[str, Any]) -> int:
    manifest_json = json.dumps(source_manifest, ensure_ascii=False)
    cur.execute(
        """
        INSERT INTO dataset_versions (version_tag, source_manifest, notes, source_hash)
        VALUES (%s, %s::jsonb, %s, md5(%s))
        ON CONFLICT (version_tag)
        DO UPDATE SET
            source_manifest = EXCLUDED.source_manifest,
            notes = EXCLUDED.notes,
            source_hash = EXCLUDED.source_hash,
            generated_at = NOW()
        RETURNING dataset_version_id;
        """,
        (
            version_tag,
            manifest_json,
            "Imported food price estimates from seeded JSON",
            manifest_json,
        ),
    )
    return int(cur.fetchone()[0])


def _ensure_price_table(cur: psycopg.Cursor) -> None:
    cur.execute(
        """
        CREATE TABLE IF NOT EXISTS food_price_estimates (
            food_id BIGINT PRIMARY KEY REFERENCES foods(food_id)
                ON UPDATE CASCADE
                ON DELETE CASCADE,
            price_100g_vnd INTEGER NOT NULL
                CHECK (price_100g_vnd > 0),
            price_category VARCHAR(80) NOT NULL,
            price_source VARCHAR(40) NOT NULL DEFAULT 'gemini',
            model_name VARCHAR(80),
            estimate_version VARCHAR(40),
            confidence_score NUMERIC(4,3) NOT NULL DEFAULT 0.700
                CHECK (confidence_score >= 0 AND confidence_score <= 1),
            source_key VARCHAR(255),
            source_name_vi VARCHAR(255),
            dataset_version_id BIGINT REFERENCES dataset_versions(dataset_version_id)
                ON UPDATE CASCADE
                ON DELETE SET NULL,
            created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
            updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
        );
        """
    )
    cur.execute("CREATE INDEX IF NOT EXISTS idx_food_price_estimates_price_100g_vnd ON food_price_estimates(price_100g_vnd);")
    cur.execute("CREATE INDEX IF NOT EXISTS idx_food_price_estimates_price_category ON food_price_estimates(price_category);")
    cur.execute("CREATE INDEX IF NOT EXISTS idx_food_price_estimates_price_source ON food_price_estimates(price_source);")


def _load_food_id_by_canonical_key(cur: psycopg.Cursor) -> dict[str, int]:
    cur.execute("SELECT canonical_key, food_id FROM foods WHERE is_active = TRUE;")
    return {str(row[0]): int(row[1]) for row in cur.fetchall()}


def _iter_price_items(price_defaults: dict[str, Any]) -> list[dict[str, Any]]:
    items = price_defaults.get("items", [])
    if not isinstance(items, list):
        raise ValueError("price_defaults.items must be a list")
    return [item for item in items if isinstance(item, dict)]


def _load_price_estimates(
    cur: psycopg.Cursor,
    items: list[dict[str, Any]],
    food_id_by_key: dict[str, int],
    dataset_version_id: int,
    price_defaults: dict[str, Any],
) -> tuple[int, int]:
    inserted = 0
    skipped = 0
    global_average = _to_int(price_defaults.get("global_average_100g")) or 15000

    for item in items:
        canonical_key = _clean_text(item.get("canonical_key"))
        name_vi = _clean_text(item.get("name_vi"))
        if not canonical_key:
            skipped += 1
            continue

        food_id = food_id_by_key.get(canonical_key)
        if not food_id:
            skipped += 1
            continue

        price_100g = _to_int(item.get("price_100g"))
        if price_100g <= 0:
            price_100g = global_average

        category = _clean_text(item.get("category")) or "khong_xac_dinh"
        source_key = _clean_text(item.get("source_id")) or canonical_key
        confidence = _to_float(item.get("confidence_score"))
        if confidence <= 0:
            confidence = 0.700

        model_name = _clean_text(item.get("model_name")) or _clean_text(price_defaults.get("summary", {}).get("model_name"))
        estimate_version = _clean_text(item.get("estimate_version")) or f"price-{_clean_text(price_defaults.get('schema_version')) or '2'}"

        cur.execute(
            """
            INSERT INTO food_price_estimates (
                food_id,
                price_100g_vnd,
                price_category,
                price_source,
                model_name,
                estimate_version,
                confidence_score,
                source_key,
                source_name_vi,
                dataset_version_id
            ) VALUES (%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)
            ON CONFLICT (food_id)
            DO UPDATE SET
                price_100g_vnd = EXCLUDED.price_100g_vnd,
                price_category = EXCLUDED.price_category,
                price_source = EXCLUDED.price_source,
                model_name = EXCLUDED.model_name,
                estimate_version = EXCLUDED.estimate_version,
                confidence_score = EXCLUDED.confidence_score,
                source_key = EXCLUDED.source_key,
                source_name_vi = EXCLUDED.source_name_vi,
                dataset_version_id = EXCLUDED.dataset_version_id,
                updated_at = NOW();
            """,
            (
                food_id,
                price_100g,
                category,
                _clean_text(item.get("price_source")) or "gemini",
                model_name,
                estimate_version,
                confidence,
                source_key,
                name_vi,
                dataset_version_id,
            ),
        )
        inserted += 1

    return inserted, skipped


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Load seeded food price estimates into PostgreSQL")
    parser.add_argument("--price-file", default=str(DEFAULT_PRICE_PATH), help="Path to price_defaults.json")
    parser.add_argument("--version-tag", default="v1.1.0-price", help="Dataset version tag for price estimates")
    parser.add_argument(
        "--reset",
        action="store_true",
        help="Truncate food_price_estimates before loading",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    price_path = Path(args.price_file)
    price_defaults = _load_json(price_path)

    if price_defaults.get("schema_version") != 2:
        raise ValueError("Expected price_defaults schema_version == 2")

    items = _iter_price_items(price_defaults)
    summary = price_defaults.get("summary", {}) if isinstance(price_defaults.get("summary"), dict) else {}

    with psycopg.connect(_database_url()) as conn:
        with conn.cursor() as cur:
            _ensure_price_table(cur)
            if args.reset:
                cur.execute("TRUNCATE TABLE food_price_estimates RESTART IDENTITY CASCADE;")

            dataset_version_id = _ensure_dataset_version(cur, args.version_tag, summary)
            food_id_by_key = _load_food_id_by_canonical_key(cur)
            inserted, skipped = _load_price_estimates(cur, items, food_id_by_key, dataset_version_id, price_defaults)
        conn.commit()

    print(f"Loaded {inserted} price estimates from {price_path}")
    print(f"Skipped {skipped} rows that could not be matched to foods.canonical_key")
    print(f"Dataset version: {args.version_tag}")


if __name__ == "__main__":
    main()
